// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgkereubgkfgxuhmwzwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZna2VyZXViZ2tmZ3h1aG13endlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDkxNTksImV4cCI6MjA1MTY4NTE1OX0.j8luGItq67J-4-ugC17zDrzttsildLKwDGfwXSLkdeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);